/*
 * This source file was generated by the Gradle 'init' task
 */
package org.rockydb;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Random;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        Path path = Path.of("./super.db");
        File file = path.toFile();

        NodeManager nodeManager = new NodeManager(file);

        int SIZE = 64 * 1024;
        Node root = nodeManager.readNode(1L);
        Object[][] kkk = new Object[SIZE][2];
        for (int i = 0; i < SIZE; i++) {
            kkk[i][0] = new Value(("aKey" + i).getBytes());
            kkk[i][1] = (long) i;
        }
        List<Object[]> suf = new ArrayList<>(List.of(kkk));

        Collections.shuffle(suf, new Random(123L));

        for (int i = 0; i < SIZE; i++) {
            //var res = root.addValue(new Value(("aKey" + i).getBytes()), i);
            Object[] o = suf.get(i);
            var res = root.addValue((Value) o[0], (long) o[1]);
            if (res != null) {
                root = nodeManager.writeNode(Node.BRANCH, new Value[]{res.key}, new long[]{res.left.getId(), res.right.getId()});
            }
        }


        long start = System.currentTimeMillis();
        for (int i = 0; i < SIZE; i++) {
            //var res = root.addValue(new Value(("aKey" + i).getBytes()), i);
            Object[] o = suf.get(i);
            var resp = root.get((Value) o[0]);
            System.out.println("For key:" + new String(((Value) o[0]).val()) + " the value is" + resp);
        }
        long stop = System.currentTimeMillis();

        System.out.println("Read 32 * 1024 values in: " + (stop - start) + " millis");

        System.out.println("root id : " + root.getId());


    }
}
